[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
server = "4MrxHjTHXpjwmnwLPpLjFduTePpazMExe5epoM1gDeDR"

[programs.devnet]
server = "4MrxHjTHXpjwmnwLPpLjFduTePpazMExe5epoM1gDeDR"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/janek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
