[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
server = "3WAygPLbRDLygztwB87McLbsUhGgJuvey17k9QHrAwHE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/janek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
